import json
import os

# 定义Jupyter notebook的内容
notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Gemini AI 多语言摘要生成工具"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import json\n",
    "import re\n",
    "import time\n",
    "import requests\n",
    "from datetime import datetime\n",
    "from dotenv import load_dotenv\n",
    "import psycopg2\n",
    "from psycopg2 import extras\n",
    "\n",
    "# 加载环境变量\n",
    "load_dotenv()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GeminiService:\n",
    "    def __init__(self):\n",
    "        self.api_key = os.getenv('GEMINI_API_KEY', '')\n",
    "        self.base_url = 'https://chatgpt-proxy.guomengtao.workers.dev'\n",
    "        self.available_models = [\n",
    "            'models/gemini-2.5-flash',\n",
    "            'models/gemma-3-1b-it',\n",
    "            'models/gemma-3-4b-it',\n",
    "            'models/gemma-3-27b-it',\n",
    "            'models/gemma-3n-e4b-it',\n",
    "            'models/gemma-3n-e2b-it',\n",
    "            'models/gemini-flash-latest',\n",
    "            'models/gemini-flash-lite-latest',\n",
    "            'models/gemini-2.5-flash-lite',\n",
    "            'models/gemini-2.5-flash-preview-09-2025',\n",
    "            'models/gemini-2.5-flash-lite-preview-09-2025',\n",
    "            'models/gemini-3-flash-preview',\n",
    "            'models/gemini-robotics-er-1.5-preview'\n",
    "        ]\n",
    "    \n",
    "    def generate_multi_lang_summary(self, details, model_index=0):\n",
    "        try:\n",
    "            model_name = self.available_models[model_index] if model_index < len(self.available_models) else self.available_models[0]\n",
    "            print(f'🔤 使用模型: {model_name} 生成多语言摘要...')\n",
    "            \n",
    "            prompt = '你是一位精通中文、英语、西班牙语的国际寻人专家和多语言 SEO 资深编辑。请分析以下失踪详情：\n' + details + '\n\n任务：为该案件生成中、英、西三语的 SEO 摘要（Summary）。\n\n输出格式要求（必须是合法 JSON，严禁任何额外解释）：\nJSON\n[\n  {\n    \"lang\": \"zh\",\n    \"summary\": \"（150-300字的中文摘要。结构：姓名+时间+地点；核心体貌/衣着特征；呼吁行动。）\"\n  },\n  {\n    \"lang\": \"en\",\n    \"summary\": \"（150-300 words English summary. Professional, native tone, no robotic translation.）\"\n  },\n  {\n    \"lang\": \"es\",\n    \"summary\": \"（Resumen en español de 150-300 palabras. Estilo natural y urgente para búsqueda de personas.）\"\n  }\n]\n\n字段约束准则（严格遵守数据库 NOT NULL 约束）：\nlang: 必须且只能是 zh, en, es 中的一个。\nsummary: 严禁为空。如果原文信息极少，请根据已知碎片信息进行合理扩充描述。\n\n内容策略:\n英文摘要需符合母语习惯（使用 \"Last seen wearing\", \"Anyone with information\" 等）。\n西语摘要需地道（使用 \"Visto por última vez\", \"Se solicita colaboración\" 等）。\n语言风格需庄重、客观，禁止使用感叹号。'\n",
    "            \n",
    "            # 使用代理发送请求\n",
    "            response = requests.post(\n",
    "                f'{self.base_url}/v1beta/models/{model_name.replace(\"models/\", \"")}:generateContent',\n",
    "                json={\n",
    "                    'contents': [\n",
    "                        {\n",
    "                            'parts': [\n",
    "                                {'text': prompt}\n",
    "                            ]\n",
    "                        }\n",
    "                    ]\n",
    "                },\n    "                params={'key': self.api_key}\n",
    "            )\n",
    "            response.raise_for_status()\n",
    "            data = response.json()\n",
    "            text = data['candidates'][0]['content']['parts'][0]['text']\n",
    "            \n",
    "            # 清理AI输出，确保是纯JSON\n",
    "            clean_text = re.sub(r'^```json|```$', '', text).strip()\n",
    "            summaries = json.loads(clean_text)\n",
    "            \n",
    "            # 验证输出格式\n",
    "            if not isinstance(summaries, list) or len(summaries) != 3:\n",
    "                raise ValueError('AI返回的摘要格式不正确')\n",
    "            \n",
    "            # 验证每个摘要的语言和内容\n",
    "            for summary in summaries:\n",
    "                if summary.get('lang') not in ['zh', 'en', 'es']:\n",
    "                    raise ValueError(f'无效的语言代码: {summary.get(\"lang\")}')\n",
    "                if not summary.get('summary') or summary.get('summary').strip() == '':\n",
    "                    raise ValueError(f'摘要内容为空: {summary.get(\"lang\")}')\n",
    "            return summaries\n",
    "        except Exception as e:\n",
    "            print(f'❌ Gemini AI 生成摘要失败: {e}')\n",
    "            # 如果当前模型失败，尝试下一个模型\n",
    "            if model_index < len(self.available_models) - 1:\n",
    "                print(f'🔄 尝试下一个模型 ({model_index + 1}/{len(self.available_models)})...')\n",
    "                return self.generate_multi_lang_summary(details, model_index + 1)\n",
    "            return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class DatabaseService:\n",
    "    def __init__(self):\n",
    "        self.conn = psycopg2.connect(\n",
    "            host=os.getenv('PG_HOST'),\n",
    "            port=os.getenv('PG_PORT'),\n",
    "            user=os.getenv('PG_USER'),\n",
    "            password=os.getenv('PG_PASSWORD'),\n",
    "            dbname=os.getenv('PG_DB_NAME'),\n",
    "            sslmode=os.getenv('PG_SSL', 'require')\n",
    "        )\n",
    "        self.cursor = self.conn.cursor(cursor_factory=extras.DictCursor)\n",
    "    \n",
    "    def close(self):\n",
    "        self.cursor.close()\n",
    "        self.conn.close()\n",
    "    \n",
    "    def init_task_progress(self):\n",
    "        try:\n",
    "            # 检查任务进度表是否存在\n",
    "            self.cursor.execute('SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' AND table_name = \'task_progress\'')\n",
    "            table_exists = self.cursor.fetchone()\n",
    "            \n",
    "            if not table_exists:\n",
    "                print('📋 创建任务进度表...')\n",
    "                self.cursor.execute('CREATE TABLE task_progress (task_name TEXT PRIMARY KEY, last_id INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)')\n",
    "                self.conn.commit()\n",
    "            \n",
    "            # 检查任务是否存在\n",
    "            self.cursor.execute('SELECT * FROM task_progress WHERE task_name = \'ai-summary\'')\n",
    "            task_exists = self.cursor.fetchone()\n",
    "            \n",
    "            if not task_exists:\n",
    "                print('📋 初始化任务进度...')\n",
    "                self.cursor.execute(\n",
    "                    'INSERT INTO task_progress (task_name, last_id, updated_at) VALUES (%s, %s, %s)',\n",
    "                    ['ai-summary', 0, datetime.now()]\n",
    "                )\n",
    "                self.conn.commit()\n",
    "        except Exception as e:\n",
    "            print(f'❌ 创建任务进度表失败: {e}')\n",
    "            self.conn.rollback()\n",
    "    \n",
    "    def get_task_progress(self):\n",
    "        try:\n",
    "            self.cursor.execute('SELECT * FROM task_progress WHERE task_name = \'ai-summary\'')\n",
    "            return self.cursor.fetchone()\n",
    "        except Exception as e:\n",
    "            print(f'❌ 获取任务进度失败: {e}')\n",
    "            return None\n",
    "    \n",
    "    def update_task_progress(self, last_id):\n",
    "        try:\n",
    "            self.cursor.execute(\n",
    "                'UPDATE task_progress SET last_id = %s, updated_at = %s WHERE task_name = \'ai-summary\'',\n",
    "                [last_id, datetime.now()]\n",
    "            )\n",
    "            self.conn.commit()\n",
    "        except Exception as e:\n",
    "            print(f'❌ 更新任务进度失败: {e}')\n",
    "            self.conn.rollback()\n",
    "    \n",
    "    def get_next_case(self, last_id):\n",
    "        try:\n",
    "            self.cursor.execute('SELECT * FROM missing_persons_cases WHERE id > %s ORDER BY id ASC LIMIT 1', [last_id])\n",
    "            return self.cursor.fetchone()\n",
    "        except Exception as e:\n",
    "            print(f'❌ 获取下一个案件失败: {e}')\n",
    "            return None\n",
    "    \n",
    "    def init_case_summaries_table(self):\n",
    "        try:\n",
    "            # 检查结果表是否存在\n",
    "            self.cursor.execute('SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' AND table_name = \'case_summaries\'')\n",
    "            table_exists = self.cursor.fetchone()\n",
    "            \n",
    "            if not table_exists:\n",
    "                print('📋 创建案件摘要表...')\n",
    "                self.cursor.execute('CREATE TABLE case_summaries (id SERIAL PRIMARY KEY, case_id VARCHAR(255) NOT NULL, lang VARCHAR(10) NOT NULL, summary TEXT NOT NULL, ai_model VARCHAR(50) NOT NULL DEFAULT \'models/gemini-2.5-flash\', created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)')\n",
    "                # 创建唯一索引\n",
    "                self.cursor.execute('CREATE UNIQUE INDEX idx_case_id_lang ON case_summaries (case_id, lang)')\n",
    "                self.conn.commit()\n",
    "                print('✅ 案件摘要表创建成功')\n",
    "        except Exception as e:\n",
    "            print(f'❌ 创建案件摘要表失败: {e}')\n",
    "            self.conn.rollback()\n",
    "    \n",
    "    def save_summary(self, case_id, lang, summary):\n",
    "        try:\n",
    "            # 先检查是否已存在记录\n",
    "            self.cursor.execute(\n",
    "                'SELECT * FROM case_summaries WHERE case_id = %s AND lang = %s',\n",
    "                [case_id, lang]\n",
    "            )\n",
    "            existing = self.cursor.fetchone()\n",
    "            \n",
    "            if existing:\n",
    "                # 更新记录\n",
    "                self.cursor.execute(\n",
    "                    'UPDATE case_summaries SET summary = %s, updated_at = %s WHERE case_id = %s AND lang = %s',\n",
    "                    [summary, datetime.now(), case_id, lang]\n",
    "                )\n",
    "                print(f'   🔄 更新 {lang.upper()} 摘要成功')\n",
    "            else:\n",
    "                # 插入新记录\n",
    "                self.cursor.execute(\n",
    "                    'INSERT INTO case_summaries (case_id, lang, summary, ai_model, created_at, updated_at) VALUES (%s, %s, %s, %s, %s, %s)',\n",
    "                    [case_id, lang, summary, 'models/gemini-2.5-flash', datetime.now(), datetime.now()]\n",
    "                )\n",
    "                print(f'   📝 插入 {lang.upper()} 摘要成功')\n",
    "            \n",
    "            self.conn.commit()\n",
    "            \n",
    "            # 验证数据是否成功写入\n",
    "            self.cursor.execute(\n",
    "                'SELECT * FROM case_summaries WHERE case_id = %s AND lang = %s',\n",
    "                [case_id, lang]\n",
    "            )\n",
    "            verify_result = self.cursor.fetchone()\n",
    "            \n",
    "            if verify_result:\n",
    "                # 验证所有必填字段\n",
    "                if not verify_result['case_id'] or not verify_result['lang'] or not verify_result['summary'] or not verify_result['ai_model']:\n",
    "                    print(f'   ❌ 验证失败: {lang.upper()} 摘要字段不完整')\n",
    "                    return False\n",
    "                \n",
    "                # 验证关键数据一致性\n",
    "                if verify_result['case_id'] != case_id or verify_result['lang'] != lang:\n",
    "                    print(f'   ❌ 验证失败: {lang.upper()} 摘要数据不一致')\n",
    "                    return False\n",
    "                \n",
    "                # 验证摘要内容不为空\n",
    "                if verify_result['summary'].strip() == '':\n",
    "                    print(f'   ❌ 验证失败: {lang.upper()} 摘要内容为空')\n",
    "                    return False\n",
    "                \n",
    "                print(f'   ✅ {lang.upper()} 摘要保存并验证成功')\n",
    "                return True\n",
    "            else:\n",
    "                print(f'   ❌ 验证失败: {lang.upper()} 摘要未找到')\n",
    "                return False\n",
    "        except Exception as e:\n",
    "            print(f'   ❌ 保存 {lang.upper()} 摘要失败: {e}')\n",
    "            self.conn.rollback()\n",
    "            return False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GeminiSummaryRunner:\n",
    "    def __init__(self):\n",
    "        self.gemini_service = GeminiService()\n",
    "        self.db_service = DatabaseService()\n",
    "    \n",
    "    def clean_html(self, html):\n",
    "        # 移除HTML标签\n",
    "        text = re.sub(r'<[^>]*>', ' ', html)\n",
    "        # 移除多余空格\n",
    "        text = re.sub(r'\s+', ' ', text).strip()\n",
    "        # 截取前2000字符（避免超出API限制）\n",
    "        return text[:2000]\n",
    "    \n",
    "    def run(self):\n",
    "        try:\n",
    "            print('🚀 启动Gemini AI多语言摘要生成服务...')\n",
    "            \n",
    "            # 1. 初始化任务进度\n",
    "            self.db_service.init_task_progress()\n",
    "            \n",
    "            # 2. 获取当前任务进度\n",
    "            task_progress = self.db_service.get_task_progress()\n",
    "            if not task_progress:\n",
    "                print('❌ 任务进度记录不存在')\n",
    "                return\n",
    "            \n",
    "            last_id = task_progress['last_id']\n",
    "            \n",
    "            # 3. 获取下一个案件\n",
    "            next_case = self.db_service.get_next_case(last_id)\n",
    "            if not next_case:\n",
    "                print('✅ 所有案件已处理完毕')\n",
    "                return\n",
    "            \n",
    "            id = next_case['id']\n",
    "            case_id = next_case['case_id']\n",
    "            case_html = next_case['case_html']\n",
    "            \n",
    "            if not case_html:\n",
    "                print(f'❌ 案件 {case_id} (ID: {id}) 无HTML内容，跳过')\n",
    "                self.db_service.update_task_progress(id)\n",
    "                return\n",
    "            \n",
    "            print(f'📋 处理案件: {case_id} (ID: {id})')\n",
    "            \n",
    "            # 4. 清理HTML内容，提取纯文本\n",
    "            clean_text = self.clean_html(case_html)\n",
    "            \n",
    "            # 5. 使用Gemini AI生成多语言摘要\n",
    "            summaries = self.gemini_service.generate_multi_lang_summary(clean_text)\n",
    "            if not summaries:\n",
    "                print(f'❌ 案件 {case_id} 摘要生成失败，跳过')\n",
    "                self.db_service.update_task_progress(id)\n",
    "                return\n",
    "            \n",
    "            # 6. 初始化摘要表\n",
    "            self.db_service.init_case_summaries_table()\n",
    "            \n",
    "            # 7. 将结果写入数据库\n",
    "            saved_languages = []\n",
    "            for summary in summaries:\n",
    "                lang = summary['lang']\n",
    "                content = summary['summary']\n",
    "                if self.db_service.save_summary(case_id, lang, content):\n",
    "                    saved_languages.append(lang)\n",
    "            \n",
    "            # 8. 总体验证\n",
    "            if len(saved_languages) == len(summaries):\n",
    "                print(f'✅ 所有摘要（{', '.join(saved_languages)}）保存并验证成功')\n",
    "            else:\n",
    "                print(f'⚠️ 部分摘要保存失败，成功的语言：{', '.join(saved_languages)}')\n",
    "            \n",
    "            # 9. 更新任务进度\n",
    "            self.db_service.update_task_progress(id)\n",
    "        except Exception as e:\n",
    "            print(f'🚨 执行错误: {e}')\n",
    "            import traceback\n",
    "            traceback.print_exc()\n",
    "        finally:\n",
    "            self.db_service.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 运行Gemini摘要生成工具\n",
    "if __name__ == '__main__':\n",
    "    runner = GeminiSummaryRunner()\n",
    "    runner.run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

# 写入有效的JSON文件
with open('test.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print('✅ 成功生成有效的test.ipynb文件')