import { readFileSync } from 'fs';
import { Client } from 'pg';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { config } from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// 加载环境变量
config({ path: `${__dirname}/../.env` });

// 从URL中提取拉丁名
function extractLatinNameFromUrl(url) {
    try {
        const urlObj = new URL(url);
        const latinNameParam = urlObj.searchParams.get('LatinName');
        if (latinNameParam) {
            // 将URL编码的+号替换为空格
            return latinNameParam.replace(/\+/g, ' ');
        }
        return null;
    } catch (error) {
        console.error(`解析URL失败: ${url}`, error);
        return null;
    }
}

// 初始化PostgreSQL客户端
function initPostgresClient() {
    // 构建连接字符串，使用更简单的SSL配置
    const connectionString = `postgresql://${process.env.PG_USER}:${process.env.PG_PASSWORD}@${process.env.PG_HOST}:${process.env.PG_PORT}/${process.env.PG_DB_NAME}?sslmode=no-verify`;
    
    console.log('正在初始化PostgreSQL客户端...');
    console.log(`连接URL: postgresql://${process.env.PG_USER}:***@${process.env.PG_HOST}:${process.env.PG_PORT}/${process.env.PG_DB_NAME}?sslmode=no-verify`);
    
    return new Client({
        connectionString: connectionString,
        ssl: {
            rejectUnauthorized: false // 完全忽略SSL证书验证
        }
    });
}

// 检查数据库连接
async function testDatabaseConnection(client) {
    try {
        console.log('正在测试数据库连接...');
        await client.connect();
        const result = await client.query('SELECT NOW() as current_time');
        console.log('数据库连接测试成功！当前时间:', result.rows[0].current_time);
        return true;
    } catch (error) {
        console.error('数据库连接测试失败:', error);
        return false;
    }
}

// 检查表是否存在，如果不存在则创建
async function ensureTableExists(client) {
    try {
        console.log('检查raw_plants表是否存在...');
        
        const checkTableQuery = `
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'raw_plants'
            );
        `;
        
        const result = await client.query(checkTableQuery);
        const tableExists = result.rows[0].exists;
        
        if (!tableExists) {
            console.log('raw_plants表不存在，正在创建...');
            
            const createTableQuery = `
                CREATE TABLE IF NOT EXISTS public.raw_plants ( 
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    latin_name TEXT NOT NULL UNIQUE, 
                    common_name TEXT, 
                    source_url TEXT NOT NULL, 
                    raw_html TEXT NOT NULL, 
                    status TEXT DEFAULT 'pending', 
                    error_log TEXT, 
                    created_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'PRC'), 
                    updated_at TIMESTAMPTZ DEFAULT (now() AT TIME ZONE 'PRC') 
                );
                
                CREATE INDEX IF NOT EXISTS idx_raw_plants_latin_name ON public.raw_plants(latin_name); 
                CREATE INDEX IF NOT EXISTS idx_raw_plants_status ON public.raw_plants(status); 
                CREATE INDEX IF NOT EXISTS idx_raw_plants_url ON public.raw_plants(source_url);
            `;
            
            await client.query(createTableQuery);
            console.log('raw_plants表创建成功！');
        } else {
            console.log('raw_plants表已存在');
        }
        
        return true;
    } catch (error) {
        console.error('检查/创建表失败:', error);
        return false;
    }
}

// 批量插入数据到数据库
async function insertPlantLinksToDatabase(client, plantLinks) {
    const batchSize = 100; // 每批处理100条记录
    let successCount = 0;
    let errorCount = 0;
    
    console.log(`开始插入 ${plantLinks.length} 条植物链接到数据库...`);
    
    for (let i = 0; i < plantLinks.length; i += batchSize) {
        const batch = plantLinks.slice(i, i + batchSize);
        const batchNumber = Math.floor(i / batchSize) + 1;
        const totalBatches = Math.ceil(plantLinks.length / batchSize);
        
        console.log(`\n处理批次 ${batchNumber}/${totalBatches} (${batch.length} 条记录)...`);
        
        const values = [];
        const placeholders = [];
        let paramIndex = 1;
        
        batch.forEach(url => {
            const latinName = extractLatinNameFromUrl(url);
            
            if (latinName !== null) {
                values.push(latinName, null, url, '', 'pending', null);
                placeholders.push(`($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3}, $${paramIndex + 4}, $${paramIndex + 5})`);
                paramIndex += 6;
            }
        });
        
        if (values.length === 0) {
            console.log(`批次 ${batchNumber} 没有有效数据，跳过`);
            continue;
        }
        
        const insertQuery = `
            INSERT INTO raw_plants (latin_name, common_name, source_url, raw_html, status, error_log) 
            VALUES ${placeholders.join(', ')}
            ON CONFLICT (latin_name) DO NOTHING
            RETURNING id;
        `;
        
        try {
            const result = await client.query(insertQuery, values);
            console.log(`批次 ${batchNumber} 插入成功，插入了 ${result.rowCount} 条记录`);
            successCount += result.rowCount;
        } catch (error) {
            console.error(`批次 ${batchNumber} 插入失败:`, error);
            errorCount += batch.length;
        }
        
        // 添加延迟以避免过快的请求
        if (i + batchSize < plantLinks.length) {
            await new Promise(resolve => setTimeout(resolve, 100));
        }
    }
    
    return { successCount, errorCount };
}

// 主函数
async function main() {
    const client = initPostgresClient();
    
    try {
        console.log('开始导入植物链接到PostgreSQL数据库...\n');
        
        // 读取plant_links.txt文件
        console.log('正在读取plant_links.txt文件...');
        const fileContent = readFileSync('./plant_links.txt', 'utf8');
        const plantLinks = fileContent.split('\n').filter(line => line.trim() !== '');
        
        console.log(`找到 ${plantLinks.length} 条植物链接`);
        
        // 测试数据库连接
        const isConnected = await testDatabaseConnection(client);
        if (!isConnected) {
            console.error('无法连接到数据库，程序退出');
            return;
        }
        
        // 确保表存在
        const tableReady = await ensureTableExists(client);
        if (!tableReady) {
            console.error('表创建失败，程序退出');
            return;
        }
        
        // 插入数据到数据库
        const { successCount, errorCount } = await insertPlantLinksToDatabase(client, plantLinks);
        
        console.log('\n=== 导入结果汇总 ===');
        console.log(`总链接数: ${plantLinks.length}`);
        console.log(`成功插入: ${successCount}`);
        console.log(`失败数量: ${errorCount}`);
        console.log(`成功率: ${((successCount / plantLinks.length) * 100).toFixed(2)}%`);
        
        if (successCount > 0) {
            console.log('\n数据已成功导入到PostgreSQL数据库的raw_plants表中！');
            console.log('下一步可以开始抓取植物详情数据。');
        } else {
            console.error('\n数据导入失败，请检查数据库连接和表结构。');
        }
        
    } catch (error) {
        console.error('程序执行过程中出现错误:', error);
    } finally {
        await client.end();
        console.log('\n数据库连接已关闭');
    }
}

// 运行主函数
main();